version: '3.5'

services:
  vocabuilt:
    networks:
      - vocabuilt_network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200

networks:
  vocabuilt_network:
    external: false